# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "steveliles/debian-7.4.0-xfce"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "1536"]
  end

  config.vm.synced_folder "../../projects", "/home/vagrant/projects"

  config.vm.provision :shell, :path => "bootstrap.sh"

end
